language: go
go_import_path: github.com/skydive-project/skydive

go:
    - 1.6

sudo: required
dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y openvswitch-switch unzip docker.io build-essential flex bison libxml2-dev libz-dev liblzma-dev libicu-dev libc++-dev bridge-utils libdb5.1-dev
    - sudo ovs-vsctl show
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

    - git clone https://github.com/the-tcpdump-group/libpcap.git
    - cd libpcap
    - git checkout libpcap-1.5.3
    - ./configure --prefix=/usr/local --disable-shared --disable-dbus --disable-bluetooth --disable-canusb
    - make
    - sudo make install
    - cd ..

    - wget https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.0.0.tar.gz
    - tar -xvzf iproute2-4.0.0.tar.gz
    - cd iproute2-4.0.0
    - make
    - sudo make install
    - cd ..

    - mkdir ${HOME}/protoc
    - pushd ${HOME}/protoc
    - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
    - unzip protoc-3.1.0-linux-x86_64.zip
    - popd
    - export PATH=${HOME}/protoc/bin:${PATH}

script:
    - export BUILD_TAG=$(date +%Y-%m-%d).${TRAVIS_JOB_NUMBER}

    - make install
    - make static
    - ./coverage.sh --coveralls

    - echo "--- DOCKER IMAGE ---"
    - make docker-image DOCKER_IMAGE=${DOCKER_IMAGE} DOCKER_TAG=${BUILD_TAG}
    - sudo docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - sudo docker tag ${DOCKER_IMAGE}:${BUILD_TAG} ${DOCKER_IMAGE}:latest
    - sudo docker push docker.io/${DOCKER_IMAGE}:${BUILD_TAG}
    - sudo docker push docker.io/${DOCKER_IMAGE}:latest

    - echo "--- BINARIES ---"
    - git remote add binaries ${BINARIES_REPO}
    - git fetch binaries
    - git checkout -b travis-builds binaries/travis-builds
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - mkdir ${BUILD_TAG}
    - cp ${GOPATH}/bin/skydive ${BUILD_TAG}/
    - git add ${BUILD_TAG}/skydive
    - test -L latest && unlink latest
    - ln -s ${BUILD_TAG} latest
    - git add latest
    - git commit -m "${BUILD_TAG} travis build"
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > .git/credentials
    - git push -q binaries travis-builds
