---
- include_role:
    name: skydive_common
    tasks_from: systemd
  vars:
    service_name: skydive-analyzer
    exec_start: "{{ skydive_binary_location }} analyzer --conf /etc/skydive/skydive.yml"
    user: "{{ skydive_sys_username }}"
    group: "{{ skydive_sys_groupname }}"
