---
- name: Make the docker image available
  include_role:
    name: skydive_common
    tasks_from: docker
  vars:
    skydive_docker_image: "{{ skydive_analyzer_docker_image }}"

- name: Create systemd unit file
  include_role:
    name: skydive_common
    tasks_from: systemd
  vars:
    service_name: skydive-analyzer
    exec_start_pre: /usr/bin/docker stop skydive-analyzer-{{ ansible_hostname }}
    exec_start: |
      /usr/bin/docker run --rm \
        {{ skydive_analyzer_docker_extra_env }} --name=skydive-analyzer-{{ ansible_hostname }} \
        --user {{ skydive_sysuser_result.uid }}:{{ skydive_sysuser_result.group }} \
        -v /etc/skydive/skydive.yml:/etc/skydive.yml \
        -v /var/lib/skydive:/var/lib/skydive \
        -p {{ skydive_analyzer_port }}:{{ skydive_analyzer_port }} \
        -p {{ skydive_analyzer_port }}:{{ skydive_analyzer_port }}/udp \
        -p {{ skydive_etcd_port }}:{{ skydive_etcd_port }} \
        -p {{ skydive_etcd_port + 1 }}:{{ skydive_etcd_port + 1 }} \
        {{ skydive_docker_registry }}/{{ skydive_analyzer_docker_image }}:{{ skydive_docker_image_tag }} \
        {{ skydive_analyzer_docker_command }}
    exec_stop_post: /usr/bin/docker stop skydive-analyzer-{{ ansible_hostname }}
    user: root
    group: root
