---
- name: Set fabric facts
  set_fact:
    skydive_fabric: |
      {% set comma = joiner(",") %}
      [ {% for item in groups['agents'] -%}
      {{ comma() }}"{{ skydive_fabric_tor_name | upper }}[Name={{ skydive_fabric_tor_name }}] -> {{ skydive_fabric_tor_name | upper }}_PORT{{ loop.index }}[Name=port{{ loop.index }}, MTU={{ skydive_fabric_tor_mtu }}]",
      "{{ skydive_fabric_tor_name | upper }}_PORT{{ loop.index }} -> *[Type=host,Name={{ hostvars[item].ansible_hostname }}]/{{ skydive_fabric_default_interface }}"
      {%- endfor %} ]
  when: skydive_auto_fabric|bool and skydive_fabric is undefined

- name: Determine analyzer IP
  set_fact:
    skydive_analyzer_ip: >-
        {%- if skydive_listen_ip is defined -%}
          {{ skydive_listen_ip }}
        {%- elif skydive_nic is defined -%}
          {{ hostvars[inventory_hostname][skydive_nic].ipv4.address }}
        {%- else -%}
          {{ hostvars[inventory_hostname].ansible_default_ipv4.address }}
        {%- endif -%}

- include: config.yml

- include: docker.yml
  when: skydive_deployment_mode == "container"

- include: package.yml
  when: skydive_deployment_mode == "package"

- include: binary.yml
  when: skydive_deployment_mode == "binary"

- include: keystone.yml
  when: skydive_auth_type == "keystone"
