---
skydive_release: v0.17.0
skydive_docker_registry: docker.io
skydive_docker_image: "skydive/skydive"
skydive_docker_image_tag: latest
skydive_config_file: /etc/skydive/skydive.yml
skydive_binary_location: /usr/bin/skydive
skydive_binary_remote_location: https://github.com/skydive-project/skydive/releases/download/{{ skydive_release }}/skydive
skydive_deployment_mode: binary
skydive_analyzer_port: 8082
skydive_agent_port: 8081
skydive_flow_protocol: udp

skydive_auth_type:
skydive_username: skydive
skydive_password: skydive

skydive_os_service_username: skydive
skydive_os_service_password: skydive
skydive_os_service_tenant_name: service
skydive_os_service_domain_name: Default
skydive_os_service_region_name: RegionOne
skydive_os_service_endpoint_type: internal
